refactor
JJTech0130/ValidationRelay pull request #12
Opened 2024-10-26 04:26 UTC by cameronaaron

2024-10-26 21:27 UTC, JJTech0130 requested changes
Xcode immediately fails to compile... have you *tested* any of this?
Or did you just forget to commit some necessary changes?

2024-10-26 21:27 UTC, JJTech0130 commented on ValidationRelay/ContentView.swift
> +    @StateObject private var relayConnectionManager = RelayConnectionManager()
```swift
ValidationRelayApp.swift:14:49: error: argument passed to call that takes no arguments
            ContentView(relayConnectionManager: RelayConnectionManager())
                       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```
You forgot to remove the argument in https://github.com/cameronaaron/ValidationRelay/blob/f549171f637871837321c257d4dd2d35c8f3b7be/ValidationRelay/ValidationRelayApp.swift#L14 where this is constructed

2024-10-26 21:27 UTC, JJTech0130 commented on ValidationRelay/Relay.swift
> +            manager?.logItems.log("Current URL is nil", isError: true)
```swift
Relay.swift:121:20: error: cannot use optional chaining on non-optional value of type 'RelayConnectionManager'
            manager?.logItems.log("Current URL is nil", isError: true)
            ~~~~~~~^
```
`manager` is a local variable here (from the init argument) that is non-optional

2024-10-26 21:27 UTC, JJTech0130 commented on ValidationRelay/Relay.swift
> +                        if let validationData = generateValidationData() {
```swift
Relay.swift:216:28: error: initializer for conditional binding must have Optional type, not 'Data'
                        if let validationData = generateValidationData() {
                           ^                    ~~~~~~~~~~~~~~~~~~~~~~~~
```
`generateValidationData()` does not return an `Optional`

2024-10-26 21:27 UTC, JJTech0130 commented on ValidationRelay/ContentView.swift
> +struct ContentView_Previews: PreviewProvider {
Why are you using a manual `PreviewProvider` rather than the macro?

2024-10-27 00:01 UTC, cameronaaron commented
@JJTech0130 Hey I'm just seeing this. These things are fixed on my end and it complies fine in Xcode. I think I never pushed my last commit. I also have a video of it working in the simulator. I'm out rn but push when I'm back. Hope you like where I am at least trying to go with the changes

2024-10-27 17:02 UTC, cameronaaron commented
commited

https://github.com/user-attachments/assets/a5c7bd5f-6d3a-4e8e-9d98-ec0a33aceed0

2024-10-27 21:46 UTC, cameronaaron commented
[ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17535520/ValidationRelay.tipa.zip)

2024-10-27 22:07 UTC, cameronaaron commented
[ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17535564/ValidationRelay.tipa.zip)

2024-10-27 22:10 UTC, cameronaaron commented
[ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17535590/ValidationRelay.tipa.zip)

2024-10-27 22:23 UTC, cameronaaron commented
tested on iphone 7 was able to reset up open bubbles with the new relay code and tested recovery from bad network

2024-10-27 22:53 UTC, JJTech0130 reviewed
Don't mean to be nitpicky, it just seems like a lot of changes that introduce complexity.

2024-10-27 22:53 UTC, JJTech0130 commented on ValidationRelay/ContentView.swift
> +                customURLError = "Invalid URL"
The old way of indicating an error was to just force the slider over to the default "Beeper"-- considering it is rare for users to ever enter a custom URL, this extra error handling seems a bit overcomplicated

2024-10-27 22:53 UTC, JJTech0130 commented on ValidationRelay/Relay.swift
> +    guard let uniqueDeviceID = MGCopyAnswer("UniqueDeviceID" as CFString)?.takeRetainedValue() as? String else {
This stuff should never fail: if it did, `absd` would have been unable to generate validation data (it uses the same API

2024-10-27 22:53 UTC, JJTech0130 commented on ValidationRelay/Relay.swift
> +    var connection: WebSocketConnection?
Why should a delegate be kept around with a nil WebSocketConnection?

2024-10-27 22:53 UTC, JJTech0130 commented on ValidationRelay/Relay.swift
> +            manager.logItems.log("Current URL is nil", isError: true)
This shouldn't be a user facing error: ever reaching this state is a logic bug

2024-10-27 22:53 UTC, JJTech0130 commented on ValidationRelay/Relay.swift
> +        DispatchQueue.main.async {
Is there a reason to do this on the main queue?

2024-10-28 21:10 UTC, cameronaaron commented
> Don't mean to be nitpicky, it just seems like a lot of changes that introduce complexity. Trying to keep the app simple and understandable, so if there isn't an obvious reason for doing something (if it is a weird Swift edge-case) a comment would be nice.

No you're not being nitpicky maybe I was being nit-picky. You know the codebase and it's edge cases better than I do so if you feel like this is going to cause more complexity than good that is very valid, please feel free to take from it what you want. Maybe if I feel inspired enough i'll just keep working on my own fork idk

2025-01-26 17:48 UTC, closed without merging